### ISSUE TITLE
The command npx @thebcms/cli create next starter always downloads the simple-blog template

### ISSUE THREAD

**Issue by Brinxx06** [bcms/starters#44]
Hello,

When I try to init the agency starter project with the provided command 

`npx @thebcms/cli create next starter agency`

It downloads the simple-blog instead.

Am I doing something wrong ?

**Comment by Bbanez** [comment]
Hey @Brinxx06 ,

Thank you for trying BCMS and opening this issue. You are doing everything correctly. The reason the simple-blog was always created is because we did not add the newly added starters to `info.json`, and because of that, the CLI did not know that they were ready for use.

The commit below should solve the issue that you were encountering. Just keep in mind that not all starters are yet ready for all frameworks. We are working hard to make them available as soon as possible.

https://github.com/bcms/starters/commit/d0f6307a951208ef2f95986cabbc6428f758452e
